### PR TITLE
test fix

### PR DESCRIPTION
**Pull request by timbalam**
Remove import and call to removed function.

### CODE REVIEW

**Comment by timbalam** [comment]
@wwood hey could you see if this fixes the first failing test? Cheers.

**Comment by wwood** [comment]
Here's what I get
```
======================================================================
ERROR: test_hierarchy.test_linkage_from_reachability
Y encodes weighted distances for pairs:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/dx60jjrjvh44q88r6kc2m1jscfda5r44-profile/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/srv/home/uqbwoodc/git/GroopM/groopm/tests/test_hierarchy.py", line 386, in test_linkage_from_reachability
    assert_true(equal_arrays(linkage_from_reachability(d), Z),
TypeError: linkage_from_reachability() takes exactly 2 arguments (1 given)

----------------------------------------------------------------------
Ran 28 tests in 268.352s

FAILED (errors=1)
```
Looks like a legitimate error. For the rest, maybe some annotation so that the tests are skipped by default is in order.

**Comment by timbalam** [comment]
Trying again with the right arguments. Not sure how to do the annotation thing, but sounds like a good idea.

**Comment by wwood** [comment]
For example like this https://github.com/warner/python-ecdsa/pull/15/commits/b7d193c5ad8741fa5e496ca26585f325ef2d5469#diff-0cec0d9003b07a58751d1fde0ff2be94R339

All the tests ran just fine for me now. Ta.

**Pull request merged**
